# Generated by Django 5.0.2 on 2024-04-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='id_tiposolicitud',
            field=models.ForeignKey(blank=True, db_column='id_tiposolicitud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tiposolicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_detallesolicitud',
            field=models.ForeignKey(blank=True, db_column='id_detallesolicitud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.detallesolicitud'),
        ),
    ]
