# Generated by Django 5.0.2 on 2024-04-21 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='cod_dpto',
            field=models.ForeignKey(blank=True, db_column='cod_dpto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamentos'),
        ),
        migrations.AddField(
            model_name='poblados',
            name='cod_municipio',
            field=models.ForeignKey(blank=True, db_column='cod_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.municipios'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cod_dpto',
            field=models.ForeignKey(blank=True, db_column='cod_dpto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.departamentos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cod_municipio',
            field=models.ForeignKey(blank=True, db_column='cod_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.municipios'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cod_poblado',
            field=models.ForeignKey(blank=True, db_column='cod_poblado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.poblados'),
        ),
    ]
