# Generated by Django 5.0.2 on 2024-04-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_detallesolicitud_id_tiposolicitud_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiposolicitud',
            table='TipoSolicitud',
        ),
    ]
