# Generated by Django 5.0.2 on 2024-04-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_tiposolicitud_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
