# Generated by Django 5.0.2 on 2024-04-21 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_poblacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poblacion',
            old_name='cod_poblado',
            new_name='cod_poblacion',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cod_poblacion',
            field=models.ForeignKey(blank=True, db_column='cod_poblacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.poblacion'),
        ),
    ]
