# Generated by Django 5.0.2 on 2024-04-21 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_userprofile_id_iden_userprofile_id_doc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='id_userprofile',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='id_userprofile',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='archivo',
            field=models.FileField(upload_to='archivos/'),
        ),
    ]
