# Generated by Django 5.0.2 on 2024-04-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0003_userprofile_last_login_alter_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
