# Generated by Django 5.0.2 on 2024-04-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0005_userprofile_last_login_userprofile_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
