# Generated by Django 5.0.2 on 2024-03-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcer',
            fields=[
                ('id_mcer', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'mecr',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Merl',
        ),
    ]
