# Generated by Django 5.0.2 on 2024-03-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_mcer_delete_merl'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mcer',
            table='mcer',
        ),
        migrations.AlterModelTable(
            name='nivelformacion',
            table='nivelformacion',
        ),
        migrations.AlterModelTable(
            name='programaformacion',
            table='programaformacion',
        ),
        migrations.AlterModelTable(
            name='resultadosaprendizaje',
            table='resultadosaprendizaje',
        ),
        migrations.AlterModelTable(
            name='tiposolicitud',
            table='tiposolicitud',
        ),
        migrations.AlterModelTable(
            name='tpcurso',
            table='tpcurso',
        ),
        migrations.AlterModelTable(
            name='tpestado',
            table='tpestado',
        ),
    ]
