# Generated by Django 5.0.2 on 2024-03-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_alter_mcer_table_alter_nivelformacion_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Competencia',
        ),
        migrations.DeleteModel(
            name='Estadoxinstru',
        ),
        migrations.DeleteModel(
            name='Ficha',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Jornada',
        ),
        migrations.DeleteModel(
            name='Mcer',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='NivelFormacion',
        ),
        migrations.DeleteModel(
            name='Poblacion',
        ),
        migrations.DeleteModel(
            name='ProgramaFormacion',
        ),
        migrations.DeleteModel(
            name='ResultadosAprendizaje',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
        migrations.DeleteModel(
            name='Tipodocumento',
        ),
        migrations.DeleteModel(
            name='TipoSolicitud',
        ),
        migrations.DeleteModel(
            name='TpCurso',
        ),
        migrations.DeleteModel(
            name='TpEstado',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
